# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 5, 20, 48, 22, 211587, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
